# Generated by Django 3.1.5 on 2021-01-22 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(blank=True, choices=[('Applicane', 'Applicant'), ('Employer', 'Employer')], default='Applicant', max_length=35, null=True),
        ),
    ]
