# Generated by Django 3.1.5 on 2021-01-24 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20210123_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('Applicant', 'Applicant'), ('Employer', 'Employer')], max_length=35),
        ),
    ]
