# Generated by Django 3.1.6 on 2021-02-16 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_auto_20210216_1605'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employerprofile',
            name='company_name',
        ),
    ]
