# Generated by Django 3.1.5 on 2021-01-22 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='created_at',
            new_name='posted_at',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='created_by',
            new_name='posted_by',
        ),
    ]
