# Generated by Django 3.1.6 on 2021-02-16 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_auto_20210216_0328'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='content',
            new_name='experience_details',
        ),
        migrations.AddField(
            model_name='application',
            name='skills',
            field=models.CharField(default='Django', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='application',
            name='experience',
            field=models.IntegerField(),
        ),
    ]
