# Generated by Django 3.1.5 on 2021-02-06 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0006_auto_20210206_1307'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='salary',
            new_name='salary_from',
        ),
        migrations.AddField(
            model_name='job',
            name='salary_to',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
