# Generated by Django 3.1.6 on 2021-02-16 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20210216_0328'),
        ('job', '0006_auto_20210216_0522'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.employerprofile'),
        ),
    ]
