# Generated by Django 3.1.6 on 2021-02-21 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0009_remove_job_add_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='add_category',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
